### ISSUE TITLE
code wanted！

### ISSUE THREAD

**Issue by xiyufeng2** [Mrqianduoduo/RSDet-8P-4R#1]
Can you afford a pytorch-based code?  TF version is hard for me , thank you very much!

**Comment by qianwen96** [comment]
Sorry, we don't have pytorch code at the moment. If you are interested, please join us.

**Comment by xiyufeng2** [comment]
It's my pleasure! How can I join you ?

**Comment by xiyufeng2** [comment]
what dose it mean? I didn't get it

**Comment by qianwen96** [comment]
you can contact me by email：qianwen2018@ia.ac.cn.
