### ISSUE TITLE
QUESTION ABOUT THE CONSISTENCE LOSS

### ISSUE THREAD

**Issue by tymanman** [Mrqianduoduo/RSDet-8P-4R#3]
Hi,The key point of your paper of consistence loss lies on the min-cost match of gt boxes points to quadrangle points, but I didn't find this part of code in the repo, would you like to provide some details about it, thanks.

**Comment by qianwen96** [comment]
Sorry for the late reply, you can see this part in the loss function, we reorder the points for  the min-cost match of gt boxes points to quadrangle points.
